### ISSUE TITLE
There is no option to run workflow

### ISSUE THREAD

**Issue by DistroAgnostic** [Johx22/Patch-Recovery#10]
There is no button/option to run a workflow. Kindly please add an option to run the same, sir.
https://www.dropbox.com/s/dn6xt1bmdp0fn8y/recovery.img?dl=0
![Screenshot (56)](https://user-images.githubusercontent.com/98891600/196038871-f5d54e01-1875-4a0b-904c-c3d6b00656a4.png)

**Comment by DistroAgnostic** [comment]
Since there is no button for "Run workflow" if anyone wants to patch recovery I had forked the repo, you can use it if you want to patch recovery. Link: https://github.com/killerboychetan/Patch-Recovery/actions
Also it may can fail to patch, so use this link(https://oshi.at/) for uploading recovery. also uncheck short url.

**Comment by Johx22** [comment]
There seems to be no problem here. Maybe try forking the repo again!
![Screenshot 2022-10-20 191546](https://user-images.githubusercontent.com/88674706/197003083-d68f22b6-ae9d-4ca9-ac23-19d404c3e8d6.png)

**Comment by DistroAgnostic** [comment]
Sorry sir, I guess I hadn't read properly that's why this confusion occurred. Well, I have a question, can I flash this patched recovery on a device with a locked bootloader? By the way for thanks for making this patch-recovery script :)
