### ISSUE TITLE
Remove zip verification

### ISSUE THREAD

**Issue by Skorpion96** [Johx22/Patch-Recovery#13]
Please add zip verification disabler script or something like that. I would like to have a way to flash root zips and since from fastboot is not possible maybe you can add patches to disable zip verification on recovery. Thank you

**Comment by ghost** [comment]
Can't use Magisk instead ?
Magisk app offers to patch your ROM's boot.img and then have it flashed (through fastboot I guess ?).

**Comment by Skorpion96** [comment]
The problem is with GSIs, since with them magisk doesn't work always, instead if I could flash phh superuser zip would be different
