### ISSUE TITLE
Patch failed with exit code 2

### ISSUE THREAD

**Issue by idontknowcodingplshelp** [Johx22/Patch-Recovery#24]
![Screenshot_20230609_180158_Chrome](https://github.com/Johx22/Patch-Recovery/assets/135946540/4c71e19f-510f-47e1-a63e-101ed8ad6e6d)

**Comment by DeadPool-4422** [comment]
You're saving the file wrong

**Comment by DeadPool-4422** [comment]
Upload the file to
https://oshi.at/

And don't forget to untick both the options

* Randomize name
* Short URL 
Before uploading and then copy the generated link and paste it in the GitHub action for building the recovery

**Comment by idontknowcodingplshelp** [comment]
Help,the site said"something went wrong,try again later"

**Comment by idontknowcodingplshelp** [comment]
> Upload the file to
> https://oshi.at/
> 
> And don't forget to untick both the options
> 
> * Randomize name
> * Short URL 
> Before uploading and then copy the generated link and paste it in the GitHub action for building the recovery 

Help,the site said"something went wrong,try again later"
