### ISSUE TITLE
The tool is not working, it stops at: r.img not found

### ISSUE THREAD

**Issue by Skorpion96** [Johx22/Patch-Recovery#25]
The tool is not working, it stops at: r.img not found. You can try by yourself

**Comment by Skorpion96** [comment]
Uhm long time ago I made my own fork for another error I was getting, it was error 2, maybe you can consider to integrate it on your tool? Although my tool works locally:https://github.com/Skorpion96/Patch-Recovery
I don't even know if I had your permission for doing my own fork but since it is a tool on github it should be fine, I will try to show you the error on your tool now, give me some time to do a try.

**Comment by Skorpion96** [comment]
Ok here is your tool with the error 2:https://github.com/gta7lite/Patch-Recovery-original/actions/runs/7832959945/job/21372846190 a screenshot as well
![Screenshot_20240208-174346_Chrome](https://github.com/Johx22/Patch-Recovery/assets/39702358/9b452a47-911f-4cc3-aa00-be0b06ddf2c8)
The recovery used, not that matters as this error happens with every recovery, I just took an example recovery from a guy of a telegram group I own:https://tmpsend.com/78ziYsyG

**Comment by Skorpion96** [comment]
Seems another guy on that group I was telling about made another fork:https://github.com/Insomniac05/Samsung-Recovery-Patcher this is really genius as it is just a small modification, you can consider to integrate it on your tool honestly

**Comment by ratcoded** [comment]
I just opened an issue for this repository, did you ever get the tool to work? I made an alternative as well and put it there. For some reason most commands that use a path in the script will fail in the workflow unless a explicit path is provided

edit: upon checking the linked repository, I tried this fix as well and quickly realized that the fix does not work and will probably mess up the process

**Comment by Skorpion96** [comment]
Yes the tool with some modifications works, I did my own version as well, btw one guy told me that has been opened a new repo, this is old one and it is deprecated, that's why the tool doesn't work. That's new one:https://github.com/engineer4t/fastboot-patcher oh but that's you, so that's a custom made version as well? Interesting
