### ISSUE TITLE
it works but no effect

### ISSUE THREAD

**Issue by mohammed-saleh2007** [Johx22/Patch-Recovery#43]
i followed instractions and it created sucsessfully but there is not any thing new and stuck in the normal fastboot

**Comment by daviddean-x** [comment]
The normal fastboot is the patch, native recovery has no fastboot.

**Comment by mohammed-saleh2007** [comment]
I build a twrp now and i don't need it anymore 
But thanks for your great job btw

But what I was saying after patching it there is no new fastboot option or accessible fastbootd on the phone
I think this is my mistake i was noob i didn't know what is vbmeta disabler
So i can close this issue and thanks again
