### ISSUE TITLE
Updated version of this repository

### ISSUE THREAD

**Issue by ratcoded** [Johx22/Patch-Recovery#54]
**There are some issues with these scripts that I've spent a while fixing, and also the version of `magiskboot` used here is outdated, so if no update to fix these issues is intended, can you archive and/or link [my](https://github.com/engineer4t/fastboot-patcher) repository to this one, so development can be moved?**

Thank you~

**Comment by ghost** [comment]
Hey there. It's me the same Johx22. Sorry for being inactive. I lost credentials to my account Johx22 hence I'm totally helpless. Please carry forward the development. Thanks a lot for your efforts.

**Comment by ghost** [comment]
I'll see if there is something I can do to regain my credentials to the other account. Thanks a lot again.

**Comment by Johx22** [comment]
Hey there. Got my account back. I shall do the needfull

**Comment by ratcoded** [comment]
You're welcome! Just as a precaution, if you don't archive the repository it'd be great if you could add a license as well. 
That's all I forgot to say.
